name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    env:
      OUTPUT_DIR: ${{ github.workspace }}/release-out
    steps:
    - uses: actions/checkout@v3
    - name: Setup vsce
      run: |
        npm install -g vsce
    - name: Build package
      run: |
        mkdir ${OUTPUT_DIR}
        RELEASE_TAG="${GITHUB_REF##*/}"
        FILE_NAME="buildg-${RELEASE_TAG}.vsix"
        SHA256SUM_FILE_NAME="${FILE_NAME}.sha256sum"
        npm install
        vsce package -o "${OUTPUT_DIR}/${FILE_NAME}"
        ( cd ${OUTPUT_DIR}; sha256sum ${FILE_NAME} ) > "${OUTPUT_DIR}/${SHA256SUM_FILE_NAME}"
    - name: Save package
      uses: actions/upload-artifact@v3
      with:
        name: builds-package
        path: ${{ env.OUTPUT_DIR }}/*

  release:
    runs-on: ubuntu-20.04
    name: Release
    needs: [build]
    env:
      OUTPUT_DIR: ${{ github.workspace }}/builds
    steps:
    - uses: actions/checkout@v3
    - name: Download Builds
      uses: actions/download-artifact@v3
      with:
        path: ${{ env.OUTPUT_DIR }}
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_TAG="${GITHUB_REF##*/}"
        cat <<EOF > ${GITHUB_WORKSPACE}/release-note.txt
        ${RELEASE_TAG}

        (TBD)
        EOF
        ASSET_FLAGS=()
        ls -al ${OUTPUT_DIR}/
        for F in ${OUTPUT_DIR}/builds-package/* ; do
          ASSET_FLAGS+=("-a" "$F")
        done
        hub release create "${ASSET_FLAGS[@]}" -F ${GITHUB_WORKSPACE}/release-note.txt --draft "${RELEASE_TAG}"
